server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devchong
    password: Y2kim2A!

  jpa:
#    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        use-new-id-generator-mappings: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug
