server:
  port: 8080

spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: devchong
    password: ENC(D45xi3Qs4KPyJ/c1ekD8+2Qr+hOTXyoQ)
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
  sql:
    init:
      platform: postgres
