### 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "sysop@gmail.com",
  "password": "1234"
}
### 포스트 리스트 가져오기
GET localhost:8080/posts/list
### 포스트 리스트 가져오기(타이틀 검색)
GET localhost:8080/posts/list?title=title
### 포스트 상세 정보 가져오기
GET localhost:8080/posts/1
Content-Type: application/json

{
 "postId" : 1
}
